// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	"github.com/cidverse/normalizeci/pkg/ncispec/common"
	"github.com/stretchr/testify/mock"
)

// NCISpec is an autogenerated mock type for the NCISpec type
type NCISpec struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *NCISpec) Validate() []common.ValidationError {
	ret := _m.Called()

	var r0 []common.ValidationError
	if rf, ok := ret.Get(0).(func() []common.ValidationError); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.ValidationError)
		}
	}

	return r0
}

type mockConstructorTestingTNewNCISpec interface {
	mock.TestingT
	Cleanup(func())
}

// NewNCISpec creates a new instance of NCISpec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNCISpec(t mockConstructorTestingTNewNCISpec) *NCISpec {
	mock := &NCISpec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
